import "./globals.css";
import Header from "./Components/Header";

export const metadata = {
    title: "Dataplicity",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <Header />
                {children}
            </body>
        </html>
    );
}
